### ISSUE TITLE
Mockup project management panel

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#107]
Mockup the project management panel that will be used to control project participation and project sync. This will require adding a menu link to each project in the project list.

<img width="301" alt="screen shot 2018-10-17 at 3 22 19 pm" src="https://user-images.githubusercontent.com/1877663/47120471-ab094580-d223-11e8-9e2a-c8bf3b43933e.png">

<img width="302" alt="screen shot 2018-10-17 at 3 33 58 pm" src="https://user-images.githubusercontent.com/1877663/47120032-2538ca80-d222-11e8-895f-2aa69acca91c.png">

**Comment by dwuthrich** [comment]
meets requirements
