### ISSUE TITLE
Map Div gets dragged around instead of moving the map

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches-mobile#115]
**Screenshots**
![ezgif-5-392d812b5dfd](https://user-images.githubusercontent.com/1542229/46825751-388ef600-cd49-11e8-8b73-cac0ffbd89e2.gif)

**Ticket Background**
*   Found by: @jmunowitch

**Comment by chiatt** [comment]
@jmunowitch Should be a lot better now on all devices

**Comment by jmunowitch** [comment]
Reviewed and looks good.
