### ISSUE TITLE
App does not display correctly on iPhone X*

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches-mobile#128]
**Describe the bug**

The iPhone X line (X, X Max, XS, XS Max, XR) have bigger screens and a notch. Currently, the App does not utilize the whole screen:
 
**Screenshots**

![screen shot 2018-10-16 at 10 42 46](https://user-images.githubusercontent.com/1542229/47035986-45885c80-d130-11e8-8b40-8ab400e09ec6.png)

**Additional context**
Article here on how to fix: https://blog.phonegap.com/displaying-a-phonegap-app-correctly-on-the-iphone-x-c4a85664c493

**Ticket Background**
*   Found by: @ryan86, @jmunowitch

**Comment by chiatt** [comment]
I noticed this wasn't an issue in @dwuthrich's simulator, however, with the app extended to the full range of the screen buttons to the right and left of the notch were not responding to taps.

**Comment by chiatt** [comment]
The interface is no longer to small for the iPhone X, but too big. re #312.  Closing this ticket because #312 describes the current state of the problem more accurately.
