### ISSUE TITLE
Add the syncing dialog to the project page during project download/sync 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#132]
<img width="904" alt="synch mobile project" src="https://user-images.githubusercontent.com/815185/47120897-87072d80-d23e-11e8-93a1-90ee85755136.png">

**Comment by dwuthrich** [comment]
@cyrus note that this mock has been superceded with the following: 
<img width="904" alt="synch mobile project" src="https://user-images.githubusercontent.com/815185/47120897-87072d80-d23e-11e8-93a1-90ee85755136.png">

**Comment by apeters** [comment]
@chiatt and @dwuthrich 
Are these 2 mockups different?

**Comment by chiatt** [comment]
@apeters The remaining issue is that the bar appears at the top of the list, not at the specific item getting synced. From what I can tell, you can't put a progress bar inside, or at the bottom of, an `ons-list-item` because of the markup onsen generates during build. There may be a way to do it, but more investigation is needed.

**Comment by dwuthrich** [comment]
meets requirement
