### ISSUE TITLE
Implement a report in the resource instance report tab

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#133]
Add a mock report for a resource instance

![Screen Shot 2018-10-17 at 2.46.27 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/4a82cc2a-d552-45c2-bbe1-ac9fa4ed680a)

**Comment by chiatt** [comment]
@dwuthrich Regarding the updating of reports, I've created as separate ticket: #214

**Comment by dwuthrich** [comment]
meets requirements
