### ISSUE TITLE
Add the active resource title and icon to the top of the editor page. 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#134]
There should also be a button on the right that allows a user to open the project shortcut menu.

![Screen Shot 2018-10-17 at 2.57.40 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/20b41340-ecb1-4904-b67a-42aad59f3252)

**Comment by apeters** [comment]
@dwuthrich had conversation with me that suggests that we don't implement this.  Instead he wanted more contextual data in the header.  This is already crudely implemented in the latest and Dennis should review before we put more effort into it to clean it up.

**Comment by apeters** [comment]
@dwuthrich it looks like we just need to add the `Instance Name` in the header.  Is that correct?

![screen shot 2019-01-07 at 8 54 01 pm](https://user-images.githubusercontent.com/823773/50810418-69d28000-12be-11e9-8b25-967daad656d6.png)

**Comment by dwuthrich** [comment]
Yup, that’s right.

**Comment by dwuthrich** [comment]
Although icon is not displayed, the key requirement of this ticket is met.  Closing
