### ISSUE TITLE
Move the application list from a side splitter to its own page

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#140]
There are 2 issues with the splitter as currently impletmented:

1. If a user deletes an application, the data of the now deleted application is visible behind the splitter.
2. If a user changes their credentials to a user with different permissions the cards visible to the user with the old permissions are still visible behind the splitter.

We could route the user back to the page where they would create a new server, but they may not want to create a new one. They may just want switch to a different server that they already have saved or delete another server. 

Alternatively we could load the next application in the list if there is one and move the user to the create application page if there is no other application to load.

**Comment by apeters** [comment]
I think the best way to solve this issues and add some additional missing functionality would be to allow the header to reflect not just the current application selected but also the project list page and the current project.  Each of which could be links to their respective pages.

For example:
- the `Actor Survey` breadcrumb in the header would take you back to the page where the user can create a new instance or select an existing instance or view the map.
- the `Projects` breadcrumb would take you back to the list of projects in the application (something you currently can't do very easily)
- the `Localhost` breadcrumb would take you to the new dedicated page to manage applications and application metadata (as opposed to the current splitter).

<img width="344" alt="screen shot 2019-01-14 at 3 27 36 pm" src="https://user-images.githubusercontent.com/823773/51147925-fa561680-1810-11e9-9a4e-a0f2b60ce17e.png">

@dwuthrich and @chiatt what do you think of my proposal?

**Comment by dwuthrich** [comment]
@apeters Yeah, I think this could work with a little additional tweak:
1. Pressing the Actor Survey breadcrumb should return the user to their starting page in the project.  That is, if their first page in the project was on the New Resource page, they should be returned there.  If they started from the edit existing resource page, then that is where the breadcrumb should resolve.

2. Are you thinking that selecting an app from the proposed new applications page would open a page with a list of projects?  If so, then I think we would want a tab interface to allow users to toggle to a page that will allow them to manage the application details (e.g.: nickname, login credentials, remove app)

**Comment by apeters** [comment]
@dwuthrich both of those are good suggestions.

**Comment by dwuthrich** [comment]
meets requirement
