### ISSUE TITLE
Add app icon and splash screen images

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#172]
Currently the application icon and splash screen images default to the cordova icon. These need to be replaced with custom icons.  

Icon documentation can be found here:
https://cordova.apache.org/docs/en/latest/config_ref/images.html#configuring-icons-in-the-cli

Splashscreen docs are here:
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/

**Comment by chiatt** [comment]
@dwuthrich It looks like Alexei already solved this issue a while back.  To add icons to your build, you need to run:
`brew install imagemagick`
`yarn icons`

**Comment by dwuthrich** [comment]
meets requirement
