### ISSUE TITLE
Report content does not update when a tile is modified in the editor

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#214]
If a user changes a value in a tile in the editor or adds a tile, the report does not immediately reflect the change. A user has to exit to the project level and then navigate back to the report to see the change. Reports should update as soon as a tile value is changed.

**Comment by chiatt** [comment]
Reports also do not update when a user creates and entirely new resource instance.

**Comment by apeters** [comment]
related to #226

**Comment by dwuthrich** [comment]
meets requirements
