### ISSUE TITLE
Selecting a card in a report with no tiles should navigate a user to an empty form

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#269]
When a user double-taps a tile in a report they are navigated to the form for that tile.  However, there is no response if a user taps on a card with no tiles. 

It would be very convenient if, when a user taps on an empty card, they are navigated to an empty form for that card's corresponding tile.

**Comment by dwuthrich** [comment]
We should add a button in the right-hand side of the tile header to indicate to a user that they can jump to the data entry form associated with an empty card

**Comment by dwuthrich** [comment]
meets requirement
