### ISSUE TITLE
Enable users to join and leave a project

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#272]
We need to enable users to leave a project after they joined (by syncing the first time). One option for tracking the join status would be to record in the survey ancillary data. 

![Screen Shot 2019-01-03 at 2.33.04 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/02f289e6-f761-4a56-b46c-fe3d151002f5)

**Comment by dwuthrich** [comment]
meets requirements
