### ISSUE TITLE
Move map popup to side panel

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#274]
To be consistent with the mockups, the map popup needs to be moved into a panel on the side of the project map with the resource type icon and name above the project description.

<img width="578" alt="screen shot 2019-01-03 at 2 45 59 pm" src="https://user-images.githubusercontent.com/1877663/50665816-fd2a4f00-0f66-11e9-8b57-4f466c1c9d50.png">

**Comment by dwuthrich** [comment]
meets requirement
