### ISSUE TITLE
Add all projects menu to the project list page

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#280]
A menu needs to be added to the project list page to allow a user to delete all inactive projects, show projects a user has left, and change the visual theme of the application.

![Screen Shot 2019-01-04 at 9.16.37 AM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/f324e285-dfa6-4b46-a964-60bba3e0dccc)

**Comment by dwuthrich** [comment]
meets requirements
