### ISSUE TITLE
Support deletion of an instance

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#287]
Currently, the mobile app does not allow a user to delete an instance.

**Comment by chiatt** [comment]
On the web app provisional users cannot delete authoritative instances nor provisional instances created by other provisional users. I think the safe way to implement deletion for provisional users on mobile is to allow them to delete only those instances which they have created on the app and have not yet synced.

Authoritative users can delete any instance in the web app, but on the mobile app, allowing a user to delete an instance that others have downloaded (and may still be editing) may have important implications for sync and should be implemented carefully.

**Comment by apeters** [comment]
The way I implemented this was to allow deletion of resources that were created on the mobile app but not synced.

**Comment by dwuthrich** [comment]
meets requirements
