### ISSUE TITLE
Style Resource Instances with proper color

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#300]
The mobile app shows resource models with the color defined in Arches but not instances:

![Screen Shot 2019-01-16 at 8.53.37 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/917b07fe-793f-4482-9990-bf5ea733d2cf)
![Screen Shot 2019-01-16 at 8.53.45 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/1822bdcc-8798-4230-a4b3-cc6d23490d8f)

**Comment by chiatt** [comment]
re #243

**Comment by dwuthrich** [comment]
meets requirement
