### ISSUE TITLE
Map widget does not display existing geometries in the resource editor

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#307]
When selecting a resource instance that had been downloaded onto a mobile device for editing, the map widget in the resource report does not display pre-existing geometry tiles.

When creating a new geometry, the map widget extent in the resource report defaults to the entire project area, instead of zooming to the newly created geometry

**Comment by robgaston** [comment]
this is not actually an issue w/ the map widget, but rather an issue w/ how tiles are currently being loaded into couchdb by arches (see here: https://github.com/archesproject/arches/issues/4561)

there is nothing to fix for this on the mobile side, so far as I can tell

**Comment by dwuthrich** [comment]
closing, as this issue is not related to the map widget.
