### ISSUE TITLE
iPhone X obscures navigation URL

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#312]
The iPhone X screen layout obscures newly implemented navigation to applications and project pages:

![Screen Shot 2019-01-17 at 1.00.17 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/0f006e8c-87d1-4218-b137-16a8b3f7a58b)

**Comment by chiatt** [comment]
I don't think there has been any attempt to implement the fix in #128. The problem has just manifested itself differently because of dependency upgrades. The proposed solution from #128 is this article:

https://blog.phonegap.com/displaying-a-phonegap-app-correctly-on-the-iphone-x-c4a85664c493

**Comment by chiatt** [comment]
Also we should confirm this is an issue on a real device and not just the emulator before making any changes to the app layout. Otherwise, we could end up doing more harm than good.

**Comment by dwuthrich** [comment]
meets requirements
