### ISSUE TITLE
Map widget should display instance geometries

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#316]
The map widget should display instance geometries (using the symbology defined in Arches Map Manager).  This would allow users to rely on symbology to indentify resource model types.  The app should allow users to manage model instances as layers (like the web app's overlay).  

Zooming the map out to regional views should either cluster geometries, as defined by the Arches Map Manager.

**Comment by chiatt** [comment]
Use a circle styled with the node's color defined in the map manager.

**Comment by robgaston** [comment]
this appears to be fixed in the latest

**Comment by dwuthrich** [comment]
meets requirement
