### ISSUE TITLE
Use traditional text boxes and labels for Application login page

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#319]
The current page does not make it clear what information to provide

![Screen Shot 2019-01-17 at 2.32.23 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/a1b71415-4756-4c27-a590-7f4435bb7185)

**Comment by chiatt** [comment]
We could probably just use the same markup in the update application application page. It's more traditional than the create application page.

![screen shot 2019-01-17 at 5 44 37 pm](https://user-images.githubusercontent.com/1877663/51360344-16132400-1a80-11e9-9551-f7a34923611b.png)

**Comment by dwuthrich** [comment]
closing, as this is already supported
