### ISSUE TITLE
[Dates] Selecting a date shows up wrong in the reports

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches-mobile#324]
In a resource instance that has a date card, when you go to choose the date on the calendar widget, the app will display the date of the day before the selected date (i.e. selecting Jan 26, 2019 will show up in the text box as Jan 25, 2019). This only occurs when the element is clean and has no data entered into it.

http://g.recordit.co/sbaamnmgng.gif

**Comment by apeters** [comment]
fixed in the latest
