### ISSUE TITLE
Editing an existing survey breaks the sync function on the mobile app

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches-mobile#329]
When editing an existing active survey and adding or changing the models or users within that survey, saving those edits will break the mobile user's ability to sync to that survey. Reversing the changes on the survey editor does not fix the issue.

**Comment by chiatt** [comment]
re archesproject/arches#4401

**Comment by chiatt** [comment]
We are now locking these mobile survey features after sync after resolving: archesproject/arches#4396 and archesproject/arches#4401
