### ISSUE TITLE
Delete privileges aren't respected in the mobile app

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-mobile#336]
If a user has `read AND write` privileges on a card, then a user is allowed to delete that card (if they are the owner) even if they don't have explicit delete privileges on the card itself.

A simple way to fix this would be to require a user to have `read, write, and delete` privileges to be able to edit a card.  This would be a 5 min fix.

If on the other hand we want to separate out delete from read and write, then a more sophisticated and time consuming solution  would have to be implemented.

**Comment by dwuthrich** [comment]
@apeters Arches allows admins to define the specific privileges a user has.  So we should go with explicit read, write, delete privileges (the 5 minute fix)

**Comment by apeters** [comment]
@dwuthrich right now a user has to have `read and write` privileges on a card to be able to edit a card in the mobile app.  This includes the ability to `delete` a card even though (or even in spite of) explicit `delete` privileges have been given/revoked for a specific user.
The 5 min fix would require an admin give `read/write/delete` privileges to a user before they could see/edit cards in the mobile app.  The issue with that is that an admin might assume that if they don't give delete privileges to a user then that user wouldn't be able to delete, but would still be able to edit, a card.

**Comment by dwuthrich** [comment]
meets requirement
