### ISSUE TITLE
Date widget displays improperly in editor

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#346]
The date widget improperly includes a timestamp in the resource editor:  (assigning to @robgaston so that he can manage it with Galen)

![Screen Shot 2019-01-23 at 11.21.57 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/07e0ae54-cdee-4c36-82a1-685f8644c3e7)

**Comment by apeters** [comment]
this is already fixed in the latest
