### ISSUE TITLE
Mobile app does not download full collection associated with a concept list

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#347]
To reproduce:

1. Create a survey with the Lincoln release monument model, include the Asset Production Event branch
2. Edit an instance in the mobile app, go to the Asset Production card and attempt to type "Public House" into the Asset Type widget.  Note that the widget dropdown does not include this entry, even though it is a member of the collection.

**Comment by apeters** [comment]
this should be fixed in arches/archesproject#4499

**Comment by dwuthrich** [comment]
meets requirement
