### ISSUE TITLE
Mobile editor tile display problem in editor

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#348]
The mobile app no longer displays relevant in formation in the Lincoln Release location branch, and throws the following error:

![Screen Shot 2019-01-23 at 12.04.54 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/31cebc99-f5db-41e0-93fa-be9ca7e2a92b)

The app shows:

![Screen Shot 2019-01-23 at 12.03.10 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/6976fd64-bbda-4cbb-a713-d26e83e44373)

**Comment by apeters** [comment]
I think this is fixed in the latest

**Comment by dwuthrich** [comment]
meets requirement
