### ISSUE TITLE
Map widget fails to load when template renders before data is loaded causing error

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#374]
In the 4.3 testing graph the geojson widget fails to load. It seems this is due to the template rendering before the computed defines the featureClass is defined.

**Comment by chiatt** [comment]
To QA, add a survey with the 4.3 test data and check if you can successfully open the geojson card. The File Upload Testing survey on QA uses the 4.3 test data resource.

**Comment by dwuthrich** [comment]
meets requirements
