### ISSUE TITLE
Report page does not show all tiles in an existing instance

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#382]
When selecting an existing instance for editing, the resource report page does not display existing values in the report.

**Comment by chiatt** [comment]
Possibly related to #383?

**Comment by apeters** [comment]
@dwuthrich , can you give any more info on this?  I'm not sure how to reproduce this bug.

**Comment by dwuthrich** [comment]
Instances downloaded as part of the survey (e.g.: defined in the data card in the MSM) and that have existing geometries; the report does not show the existing geometry.

**Comment by chiatt** [comment]
@dwuthrich Is it just the geometry datatype or other datatypes as well? Maybe this could be a duplicate of #316 because it's the widget that is displayed in both the report and editor.

**Comment by robgaston** [comment]
I think this is a duplicate of #307 - that is, the tiles simply weren't being loaded prior to #4562

**Comment by dwuthrich** [comment]
closing, related to tile load logic flaw
