### ISSUE TITLE
UI usability: add a "pull to synch" message on project home page

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-mobile#393]
Initial state of the app after logging on to an app is blank.  We should add a panel that says "Pull to refresh project list" or similar to help old people like me know what to do next

![Screen Shot 2019-02-04 at 4.04.47 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/2df460e4-6dd7-4314-a7d4-b07f8d78141f)

**Comment by apeters** [comment]
@dwuthrich I'm closing this ticket because now, the project list automatically populates after you join an Arches app.

**Comment by dwuthrich** [comment]
@apeters Good that the app automatically populates the project list on login.  We should have a panel that says something like "No projects currently active" if the project list is empty.

**Comment by dwuthrich** [comment]
meets requirement
