### ISSUE TITLE
On the project page, remove "dot" navigation at bottom of page and replace with 3 "tabbed" footer .

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-mobile#66]
Detail of what the footer should look like:
![Screen Shot 2018-09-06 at 12.47.59 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/7df8da45-b78b-4d93-a1eb-2a1e76fdfc0b)

- The "New" tab corresponds to the SelectResourceTypePage.vue
- The "Review" tab corresponds to the SelectResourceInstancePage.vue
- The "Summary" page corresponds to the ProjectMapPage.vue (which should be renamed in #67 )

Full screen shot:
![Screen Shot 2018-09-06 at 12.47.48 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/3bdf5e13-032e-4089-ac71-f0ed706dc722)

The current page looks like this:
![Screen Shot 2018-09-06 at 1.12.20 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/8c6a7ba6-4057-45f1-9fb7-317a525998b2)

**Comment by chiatt** [comment]
Looks great!
