### ISSUE TITLE
Add slide out tray to project page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-mobile#68]
When a user clicks the light bulb icon show/hide the tray.
When a user clicks on one of the items in the tray, the tray may (but not always) need to be hidden.

![Screen Shot 2018-09-06 at 4.59.35 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/7247e972-8ba9-4c1f-b405-f25385128bf2)

**Comment by jmunowitch** [comment]
Based upon the latest UI design docs, (Arches MSM v5.pdf, this looks good.
