### ISSUE TITLE
Add footer to resource editor page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-mobile#72]
See the ProjectPage.vue for a working example.

![Screen Shot 2018-09-12 at 1.06.56 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/08574d9b-2abe-41e2-8cb5-ce300cc9b3df)

**Comment by jmunowitch** [comment]
It looks like there is now a footer for the resource editor page, but there are a few issues to note:

- If you drag the main screen to the left repeatedly, you will discover a new page that is not listed on the tabs.
- The Resource Tab is not using the correct name or icon.
-

**Comment by chiatt** [comment]
@jmunowitch I've updated the text and icons in the footer. Good catch regarding the hidden page. That issue needs to be addressed as part of the editing form (re #80) rather than the footer because that page is acting as a placeholder for the form and we need to find a better solution.

**Comment by jmunowitch** [comment]
Reviewed and looks good.
