### ISSUE TITLE
Create a Vue component to display the cards of a resource model

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#79]
Users will need to be able to select a card to edit. This will require a view component that will show the top level cards. If a user selects a card then sub cards will be listed and if a sub card contains tiles, selecting that sub card will segue the app to a data entry form.

![Screen Shot 2018-09-18 at 5.28.40 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/b2e7d5af-b61a-47d4-a4e8-053f8759d21f)

<img width="250" alt="screen shot 2018-09-18 at 5 33 16 pm" src="https://user-images.githubusercontent.com/1877663/45724376-adb44480-bb6a-11e8-8e68-73a86d8316bd.png">

**Comment by jmunowitch** [comment]
On my iOS emulator (and iPhone 6), the top level cards look like this:
![screen shot 2018-10-29 at 14 16 59](https://user-images.githubusercontent.com/1542229/47680913-623b8000-db85-11e8-9188-1e835e836e43.png)
I am unsure of what the plusses and > signs are. There is also a card missing from this display. @apeters thought a card may be covered from by the carousel at the bottom of the page. Perhaps converting this to Tabs, similar to what @chiatt did here may fix the problem: https://github.com/archesproject/arches-mobile/pull/144/files#diff-04059b3452db32ed2c4d4ac4028f0e34

**Comment by chiatt** [comment]
Meets requirements
