### ISSUE TITLE
Screen showing map of resources in a project

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-mobile#8]
Screen should show a summary of the project and counts of resources in the project by type.

![arches project info project summary](https://user-images.githubusercontent.com/823773/35891514-950b1c0e-0b59-11e8-8edd-9d23e9fbc812.png)

**Comment by apeters** [comment]
@robgaston , I would focus on the map portion of this page rather then the "summary" stuff at the top of the page.  I would advocate that we move that summary info into its own dedicated page (essentially #30).

**Comment by chiatt** [comment]
This ticket has been resolved by #111
