### ISSUE TITLE
Create a Vue component to display a form 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#80]
Once a user has selected a card with tiles, we will need to show a form with selected card's respective widgets.

![Screen Shot 2018-09-18 at 5.49.33 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/c3ff0a5b-aa6a-47fd-b267-f4c3cdfa48ed)

**Comment by dwuthrich** [comment]
meets requirements
