### ISSUE TITLE
Create a Vue component to support the date datatype

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#88]
Create a Vue component to allow users to edit tiles with the date datatype

**Comment by chiatt** [comment]
Onsen doesn't seem to have a date-picker component.  It's probably worth searching for something is more actively maintained, but this plugin may work: https://github.com/VitaliiBlagodir/cordova-plugin-datepicker

**Comment by dwuthrich** [comment]
meets requirements
