### ISSUE TITLE
Add ability to remove an application

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-mobile#97]
Users should be able to add and remove applications in the Add application screen.

![Screen Shot 2018-09-21 at 10.04.25 AM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/69b08e74-e81e-4a9e-8a49-009faa8871ab)

**Comment by jmunowitch** [comment]
It looks like this may not be working as intended in an emulator/on a phone:
![delete application fail](https://user-images.githubusercontent.com/1542229/47106681-1a6b3f00-d1fc-11e8-880d-95c83b37865f.gif)

**Comment by jmunowitch** [comment]
Reviewed and looks good.
